name: Victor Montoya
favicon: null
layout_spectrum: 0
typography_spectrum: 0.69497
title: Victor Montoya - Graphic Designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6f7280'
    - '#97aab0'
    - '#313e54'
    - '#a7a406'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
